version: '3.8'
services:
  ubuntu:
    image: ubuntu
    container_name: ubuntu
    volumes:
      - ../..:/home/windows
    stdin_open: true
    tty: true
  python:
    build:
      context: ./Python
      dockerfile: python.Dockerfile
    container_name: python
    volumes:
      - ../..:/home/windows
    stdin_open: true
    tty: true