version: '3.8'
services:
  ubuntu:
    image: ubuntu
    container_name: ubuntu
    volumes:
      - ../..:/home/windows
    stdin_open: true
    tty: true
  python:
    image: python:3-alpine
    container_name: python
    volumes:
      - ../..:/home/windows
    stdin_open: true
    tty: true
