version: '3.8'
services:
  ubuntu:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu.dockerfile
    container_name: ubuntu
    volumes:
      - ../..:/home
    stdin_open: true
    tty: true
  python:
    build:
      context: .
      dockerfile: dockerfiles/python.dockerfile
    container_name: python
    volumes:
      - ../Curriculo:/app
    stdin_open: true
    tty: true