version: '3.8'
services:
  ubuntu:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu.Dockerfile
    container_name: ubuntu
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
  python:
    build:
      context: .
      dockerfile: dockerfiles/python.Dockerfile
    container_name: python
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true