version: '3.8'
services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    volumes:
      - ./app:/usr/src/app
    stdin_open: true
    tty: true
  python:
    build:
      context: .
      dockerfile: dockerfiles/python.Dockerfile
    container_name: python
    volumes:
      - ./app:/usr/src/app
    stdin_open: true
    tty: true